[{"type":"message","text":"<https://github.com/vim/vim/commit/e6b5324e3a3d354363f3c48e784c42ce3e77453f|patch 8.2.1110: Vim9: line continuation does not work in function arg…>\npatch 8.2.1110: Vim9: line continuation does not work in function arguments\n\nProblem:    Vim9: line continuation does not work in function arguments.\nSolution:   Pass \"evalarg\" to get_func_tv().  Fix seeing double quoted string\n            as comment.","ts":"1593617894.139500","attachments":[{"fallback":"GitHub: patch 8.2.1110: Vim9: line continuation does not work in function arg… · vim/vim@e6b5324","id":1,"title":"patch 8.2.1110: Vim9: line continuation does not work in function arg… · vim/vim@e6b5324","title_link":"https://github.com/vim/vim/commit/e6b5324e3a3d354363f3c48e784c42ce3e77453f","text":"…uments Problem: Vim9: line continuation does not work in function arguments. Solution: Pass \"evalarg\" to get_func_tv(). Fix seeing double quoted string as comment.","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/e6b5324e3a3d354363f3c48e784c42ce3e77453f","original_url":"https://github.com/vim/vim/commit/e6b5324e3a3d354363f3c48e784c42ce3e77453f"}],"edited":{"user":"BPV6T0C1J","ts":"1593617895.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/9a78e6df17033223ebdf499f2b02b2538601c52d|patch 8.2.1111: inconsistent naming of get_list_tv() and eval_dict()>\npatch 8.2.1111: inconsistent naming of get_list_tv() and eval_dict()\n\nProblem:    Inconsistent naming of get_list_tv() and eval_dict().\nSolution:   Rename get_list_tv() to eval_list().  Similarly for eval_number(),\n            eval_string(), eval_lit_string() and a few others.","ts":"1593621497.139700","attachments":[{"fallback":"GitHub: patch 8.2.1111: inconsistent naming of get_list_tv() and eval_dict() · vim/vim@9a78e6d","id":1,"title":"patch 8.2.1111: inconsistent naming of get_list_tv() and eval_dict() · vim/vim@9a78e6d","title_link":"https://github.com/vim/vim/commit/9a78e6df17033223ebdf499f2b02b2538601c52d","text":"Problem: Inconsistent naming of get_list_tv() and eval_dict(). Solution: Rename get_list_tv() to eval_list(). Similarly for eval_number(), eval_string(), eval_lit_string() and a f...","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/9a78e6df17033223ebdf499f2b02b2538601c52d","original_url":"https://github.com/vim/vim/commit/9a78e6df17033223ebdf499f2b02b2538601c52d"}],"edited":{"user":"BPV6T0C1J","ts":"1593621498.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/5f195938d4d489aa288bdb54ee6112a34aed1df9|patch 8.2.1112: Vim9: no line continuation allowed in method call>\npatch 8.2.1112: Vim9: no line continuation allowed in method call\n\nProblem:    Vim9: no line continuation allowed in method call.\nSolution:   Handle line continuation in expression before method call.","ts":"1593627498.139900","attachments":[{"fallback":"GitHub: patch 8.2.1112: Vim9: no line continuation allowed in method call · vim/vim@5f19593","id":1,"title":"patch 8.2.1112: Vim9: no line continuation allowed in method call · vim/vim@5f19593","title_link":"https://github.com/vim/vim/commit/5f195938d4d489aa288bdb54ee6112a34aed1df9","text":"Problem: Vim9: no line continuation allowed in method call. Solution: Handle line continuation in expression before method call.","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/5f195938d4d489aa288bdb54ee6112a34aed1df9","original_url":"https://github.com/vim/vim/commit/5f195938d4d489aa288bdb54ee6112a34aed1df9"}],"edited":{"user":"BPV6T0C1J","ts":"1593627498.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/a0d072ef8203b225bd46bcd826cb3d2e3c3b941a|patch 8.2.1113: no test for verbose output of :call>\npatch 8.2.1113: no test for verbose output of :call\n\nProblem:    No test for verbose output of :call.\nSolution:   Add a test.","ts":"1593628694.140100","attachments":[{"fallback":"GitHub: patch 8.2.1113: no test for verbose output of :call · vim/vim@a0d072e","id":1,"title":"patch 8.2.1113: no test for verbose output of :call · vim/vim@a0d072e","title_link":"https://github.com/vim/vim/commit/a0d072ef8203b225bd46bcd826cb3d2e3c3b941a","text":"Problem: No test for verbose output of :call. Solution: Add a test.","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/a0d072ef8203b225bd46bcd826cb3d2e3c3b941a","original_url":"https://github.com/vim/vim/commit/a0d072ef8203b225bd46bcd826cb3d2e3c3b941a"}],"edited":{"user":"BPV6T0C1J","ts":"1593628694.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null},{"type":"message","text":"<https://github.com/vim/vim/commit/1112c0febb509d0cb219f3a2479fd36833507167|patch 8.2.1114: terminal test sometimes times out>\npatch 8.2.1114: terminal test sometimes times out\n\nProblem:    Terminal test sometimes times out.\nSolution:   Split the test in two parts.","ts":"1593634692.140300","attachments":[{"fallback":"GitHub: patch 8.2.1114: terminal test sometimes times out · vim/vim@1112c0f","id":1,"title":"patch 8.2.1114: terminal test sometimes times out · vim/vim@1112c0f","title_link":"https://github.com/vim/vim/commit/1112c0febb509d0cb219f3a2479fd36833507167","text":"Problem: Terminal test sometimes times out. Solution: Split the test in two parts.","thumb_url":"https://avatars0.githubusercontent.com/u/11618545?s=400&v=4","blocks":null,"service_name":"GitHub","service_icon":"https://a.slack-edge.com/80588/img/unfurl_icons/github.png","thumb_width":48,"thumb_height":48,"from_url":"https://github.com/vim/vim/commit/1112c0febb509d0cb219f3a2479fd36833507167","original_url":"https://github.com/vim/vim/commit/1112c0febb509d0cb219f3a2479fd36833507167"}],"edited":{"user":"BPV6T0C1J","ts":"1593634693.000000"},"subtype":"bot_message","bot_id":"BPV6T0C1J","username":"Recent Commits to vim:master","icons":{"image_48":"https://a.slack-edge.com/80588/img/services/rss_48.png"},"replace_original":false,"delete_original":false,"blocks":null}]
